// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.0--rc2
// source: proto/math.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstNum      int64                  `protobuf:"varint,1,opt,name=first_num,json=firstNum,proto3" json:"first_num,omitempty"`
	SecondNum     int64                  `protobuf:"varint,2,opt,name=second_num,json=secondNum,proto3" json:"second_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	mi := &file_proto_math_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_math_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_proto_math_proto_rawDescGZIP(), []int{0}
}

func (x *SumRequest) GetFirstNum() int64 {
	if x != nil {
		return x.FirstNum
	}
	return 0
}

func (x *SumRequest) GetSecondNum() int64 {
	if x != nil {
		return x.SecondNum
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int64                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_math_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_math_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_math_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int64                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_math_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_math_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_math_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_proto_math_proto protoreflect.FileDescriptor

const file_proto_math_proto_rawDesc = "" +
	"\n" +
	"\x10proto/math.proto\"H\n" +
	"\n" +
	"SumRequest\x12\x1b\n" +
	"\tfirst_num\x18\x01 \x01(\x03R\bfirstNum\x12\x1d\n" +
	"\n" +
	"second_num\x18\x02 \x01(\x03R\tsecondNum\"\x1c\n" +
	"\bResponse\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x03R\x03num\"\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x03R\x03num2\x91\x01\n" +
	"\vMathService\x12\x1d\n" +
	"\x03Sum\x12\v.SumRequest\x1a\t.Response\x12\x1c\n" +
	"\x03Avg\x12\b.Request\x1a\t.Response(\x01\x12%\n" +
	"\fPrimeDivisor\x12\b.Request\x1a\t.Response0\x01\x12\x1e\n" +
	"\x03Max\x12\b.Request\x1a\t.Response(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_math_proto_rawDescOnce sync.Once
	file_proto_math_proto_rawDescData []byte
)

func file_proto_math_proto_rawDescGZIP() []byte {
	file_proto_math_proto_rawDescOnce.Do(func() {
		file_proto_math_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_math_proto_rawDesc), len(file_proto_math_proto_rawDesc)))
	})
	return file_proto_math_proto_rawDescData
}

var file_proto_math_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_math_proto_goTypes = []any{
	(*SumRequest)(nil), // 0: SumRequest
	(*Response)(nil),   // 1: Response
	(*Request)(nil),    // 2: Request
}
var file_proto_math_proto_depIdxs = []int32{
	0, // 0: MathService.Sum:input_type -> SumRequest
	2, // 1: MathService.Avg:input_type -> Request
	2, // 2: MathService.PrimeDivisor:input_type -> Request
	2, // 3: MathService.Max:input_type -> Request
	1, // 4: MathService.Sum:output_type -> Response
	1, // 5: MathService.Avg:output_type -> Response
	1, // 6: MathService.PrimeDivisor:output_type -> Response
	1, // 7: MathService.Max:output_type -> Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_math_proto_init() }
func file_proto_math_proto_init() {
	if File_proto_math_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_math_proto_rawDesc), len(file_proto_math_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_math_proto_goTypes,
		DependencyIndexes: file_proto_math_proto_depIdxs,
		MessageInfos:      file_proto_math_proto_msgTypes,
	}.Build()
	File_proto_math_proto = out.File
	file_proto_math_proto_goTypes = nil
	file_proto_math_proto_depIdxs = nil
}
